version: "3"
services:
  go:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    volumes:
      - ./:/go/src
    tty: true
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp:unconfined
