# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  # The most common configuration options are documented and commented below.
  # For a complete reference, please see the online documentation at
  # https://docs.vagrantup.com.
  config.vm.synced_folder "./src/", "/home/vagrant/src/"

  config.vm.provider "virtualbox" do |vb|
    # 割り当てるメモリー(MB)
    vb.memory = 2500
    # CPUの数
    vb.cpus = 2
    # I/O APICの有効化
    #vb.customize ["modifyvm", :id, "--ioapic", "on"]
  end
  # Every Vagrant development environment requires a box. You can search for
  # boxes at https://vagrantcloud.com/search.
  config.vm.box = "centos/7"

  config.vm.provision :docker
  config.vm.provision "shell", inline: <<-SHELL
    yum install -y vim
    #コマンド確認
    curl -sSLf https://get.k0s.sh | sudo sh
    /usr/local/bin/k0s install controller --single
    /usr/local/bin/k0s start || :

  SHELL
  #config.vm.privison
end
