version: "2"
services:
  graphql:
    build: .
    volumes:
      - gunicorn-socket:/var/run/gunicorn/
      - "./:/mnt"
    ports:
        - "127.0.0.1:5000:5000"
    tty: true
    # entrypoint: gunicorn main:app --bind unix:/var/run/gunicorn/gunicorn.sock
    # gunicorn main:app --bind 0.0.0.0:5000
    # uvicorn books.app:app --reload --host 0.0.0.0 --port 5000
    entrypoint: >
      /bin/bash -c "sleep 86400"
  # nginx:
  #   image: nginx:1.18-alpine
  #   volumes:
  #     - gunicorn-socket:/var/run/gunicorn/
  #     - "./nginx.conf:/etc/nginx/nginx.conf"
  #   ports:
  #     - 6070:80
  seeding:
    build: .
    volumes:
      - "./:/mnt"
    entrypoint: >
      /bin/bash -c "sleep 86400"
  db:
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_DATABASE: test
      MYSQL_ROOT_PASSWORD: test
      MYSQL_USER: test
      MYSQL_PASSWORD: test
    ports:
      - "3306:3306"
volumes:
  gunicorn-socket:
