name: dockerize

on: [ workflow_dispatch ]

jobs:
  dockerize:
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout current branch
        uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}
      - name: test
        run: | 
          docker network create dockerize-test
          docker run --network=dockerize-test --name mysql -e MYSQL_ROOT_PASSWORD=psss -d mysql:latest
          echo "wait starting mysql ...."
          docker run --network=dockerize-test -i --entrypoint dockerize jwilder/dockerize --timeout 20s --wait tcp://mysql:3306
          docker exec -T mysql mysql 