name: Lint Dockerfile

on: push

jobs:
  dockerfile_linter:
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout current branch
        uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}
      - name: lint Dockerfile
        run: | 
          ls -al 
          for file in `find . -name 'Dockerfile'`; do
            echo -n "==========================================";
            echo -n "${file}のlinterを実行中....";
            echo -n "==========================================";
            docker run --rm -i ghcr.io/hadolint/hadolint /bin/hadolint --no-fail - < "${file}"
          done
