name: terraform

on: [workflow_dispatch]

jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout current branch
        uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}
      - name: test
        run: |
          cd terraform
          docker compose up -d 
          docker compose exec tf sh -c 'cd localstack && terraform plan'
          docker compose exec tf sh -c 'cd localstack && terraform apply --auto-approve'
